{
  "language": "java",
  "os": [
      "linux"
  ],
  "dist": "xenial",
  "sudo": true,
  "services": [
      "docker"
  ],
  "after_success": [
      "docker build -t se_methods1 .",
      "docker run se_methods1"
  ]
}